services:

  php-fpm:
    build:
      context: .
      dockerfile: ./container-conf/dniwa-php-fpm/Dockerfile
    container_name: dniwa-php-fpm
    volumes:
      - ./app/resources:/var/www/html/resources
      - ./app/app:/var/www/html/app
      - ./app/tests:/var/www/html/tests
      - ./app/database:/var/www/html/database
      - ./app/routes:/var/www/html/routes
      - ./app/config:/var/www/html/config
      - ./app/.env:/var/www/html/.env
      - ./app/vite.config.js:/var/www/html/vite.config.js
      - ./app/phpunit.xml:/var/www/html/phpunit.xml
      - vol-static:/var/www/html/public/static
      - vol-build:/var/www/html/public/build
    env_file:
      - .secrets/dniwa.env
    command: sh -c "npm run build && docker-php-entrypoint && php-fpm"
    networks:
      - dniwa

  nginx:
    build:
      context: .
      dockerfile: ./container-conf/dniwa-nginx/Dockerfile
    container_name: dniwa-nginx
    volumes:
      - vol-static:/var/www/html/public/static
      - vol-build:/var/www/html/public/build
    ports:
      - 8080:80
    networks:
      - dniwa

  mariadb:
    image: mariadb:11.1.2
    container_name: dniwa-mariadb
    volumes:
      - vol-mariadb:/var/lib/mysql
    env_file:
      - .secrets/dniwa.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    networks:
      - dniwa

networks:
  dniwa:
    name: dniwa-network

volumes:
  vol-mariadb:
  vol-static:
  vol-build:
