services:

  php-fpm:
    image: php:8.2.6-fpm
    container_name: php-fpm
    volumes:
      - ./app/:/usr/share/nginx/html

  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./container-conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/:/usr/share/nginx/html

  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb
    volumes:
      - vol-mariadb:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: dniwa
      MYSQL_USER: dniwauser
      MYSQL_PASSWORD: secret

volumes:
  vol-mariadb:
